# Generated by Django 5.2.7 on 2025-11-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_corporate_account',
            field=models.BooleanField(default=False, verbose_name='Корпоративный аккаунт'),
        ),
    ]
