# Generated by Django 5.2.7 on 2025-11-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='place_of_work',
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=100, null=True, verbose_name='Отчество'),
        ),
    ]
