# Generated by Django 5.2.7 on 2025-11-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место работы'),
        ),
    ]
